### ISSUE TITLE
Settings Screen and and global App state

### ISSUE THREAD

**Issue by itsdaveit** [itsdave-de/inside_app#3]
Create a settings screen with FrappeURL, Key and Secret Similar to:

https://github.com/itsdave-de/inside_app/blob/dave-testing/components/BackendSettingsScreen.js

Where we can store credentials.

We will need an object where we can do the REST Queries in multiple Dialogs in  the App.

If possible implement

https://github.com/The-Commit-Company/frappe-react-sdk

**Comment by itsdaveit** [comment]
We will also need a global state to make decissions, depending of beeing "online" or "offline" maybe let it toggle from the settings screen first.

**Comment by jordialbert** [comment]
New Settings page was added. Still have to work on installing Frappe React SDK, will work on it on a new Pull Request
